### ISSUE TITLE
Alpha V0.x.0 roadmap

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#442]
This issue is a high-level roadmap for all work on the alpha release. The goal is to provide:
* a transparent process for our contributors
* a space to discuss about features
* an expected release version

This issue will be updated on the go, as we work on the release.

### v0.3.0
This version is focus on the How-to section. We defined a minimalist and must have version of the section.
All the how-to data must be usable for next versions.
More informations on this section can be found in the dedicated module issue #3.

- [x] Add notification for “under development” : Beta bar at the top
- [x] Archive current `master` branch work on discussion & other section than how-to (#441)
- [ ] Update UI of pages :
    - [x] How-to list view (#419)
    - [ ] How-to create post (#440)
    - [x] How-to post view (#420)
- [x] Minimalist login flow
    - [x] Abillity to sign-up
    - [x] Ability to login with davehakkens.nl credentials
    - [x] Ability to update personnal infos (username, password)

#### Backlogs for versions 0.3.x
- How-to list view: filterbar
- Create How-to: Add tags
- Create How-to : Add project
- Create How-to : Upload multiple images per step
- Create How-to : Add embed video
- Create How-to : Add contributions guidelines    
- How-to Single view : Show video
- How-to Single view : Show compressed/scaled images
- How-to Single view : Include comments
- How-to Single view : Edit how-to
- How-to Single view : Button to “Useful” how-to’s
- How-to Single view : Button to “Save” how-to’s
- Login : Forgot password

### v0.4.0
**still design wip**
This version will be focus on the Event section.

### v0.5.0
**still design wip**
This version will be focus on the Map section.

**Comment by chrismclarke** [comment]
I think it's better to capture this information in modules threads. I've added a board which shows an overview of all the modules: https://github.com/OneArmyWorld/onearmy/projects/4

I've also copied content from this checklist into the corresponding howto and user profile modules, and created placeholder projects for the 0.4 and 0.5 versions.

Closing here
